// Components
export { default as Section } from "./section"
export { default as Footer } from "./footer"
export { default as Head } from "./head"
export { default as Layout } from "./layout"
export { default as Navigation } from "./navigation"
export { default as Service } from "./service"
export { default as Profile } from "./profile"
export { default as Menu } from "./menu"
export { default as Language } from "./language"
export { default as Form } from "./form"
export { default as ProjectList } from "./projectList"
export { default as Project } from "./project"
export { default as ProjectSwiper } from "./projectSwiper"
export { default as Projects } from "./projects"

// Sections
export { default as About } from "./Sections/about"
export { default as Community } from "./Sections/community"
export { default as Contact } from "./Sections/contact"
export { default as Home } from "./Sections/home"
export { default as Services } from "./Sections/services"
